(define (problem socs2025_match_cellar_19-problem)
 (:domain socs2025_match_cellar_19-domain)
 (:init (handfree) (= (num_matches) 21) (= (num_fuses) 42) (= (num_lit_matches) 0) (= (num_mended_fuses) 0))
 (:goal (and (= (num_mended_fuses) 42)))
 (:metric minimize (total-time))
)
