(define (problem socs2025_match_cellar_13-problem)
 (:domain socs2025_match_cellar_13-domain)
 (:init (handfree) (= (num_matches) 15) (= (num_fuses) 30) (= (num_lit_matches) 0) (= (num_mended_fuses) 0))
 (:goal (and (= (num_mended_fuses) 30)))
 (:metric minimize (total-time))
)
