(define (problem socs2025_satellite_1-problem)
 (:domain socs2025_satellite_1-domain)
 (:objects
   satellite0 - satellite
   star0 groundstation1 groundstation2 phenomenon3 phenomenon4 star5 phenomenon6 - direction
   instrument0 - instrument
   image1 spectrograph2 thermograph0 - mode
 )
 (:init (supports instrument0 thermograph0) (calibration_target instrument0 groundstation2) (= (calibration_time instrument0 groundstation2) 6) (on_board instrument0 satellite0) (power_avail satellite0) (pointing satellite0 phenomenon6) (= (data_capacity satellite0) 1000) (= (data phenomenon3 image1) 22) (= (data phenomenon4 image1) 120) (= (data star5 image1) 203) (= (data phenomenon6 image1) 144) (= (data phenomenon3 spectrograph2) 125) (= (data phenomenon4 spectrograph2) 196) (= (data star5 spectrograph2) 68) (= (data phenomenon6 spectrograph2) 174) (= (data phenomenon3 thermograph0) 136) (= (data phenomenon4 thermograph0) 134) (= (data star5 thermograph0) 273) (= (data phenomenon6 thermograph0) 219) (= (slew_time groundstation1 star0) 19) (= (slew_time star0 groundstation1) 19) (= (slew_time groundstation2 star0) 39) (= (slew_time star0 groundstation2) 39) (= (slew_time groundstation2 groundstation1) 69) (= (slew_time groundstation1 groundstation2) 69) (= (slew_time phenomenon3 star0) 15) (= (slew_time star0 phenomenon3) 15) (= (slew_time phenomenon3 groundstation1) 90) (= (slew_time groundstation1 phenomenon3) 90) (= (slew_time phenomenon3 groundstation2) 34) (= (slew_time groundstation2 phenomenon3) 34) (= (slew_time phenomenon4 star0) 36) (= (slew_time star0 phenomenon4) 36) (= (slew_time phenomenon4 groundstation1) 32) (= (slew_time groundstation1 phenomenon4) 32) (= (slew_time phenomenon4 groundstation2) 40) (= (slew_time groundstation2 phenomenon4) 40) (= (slew_time phenomenon4 phenomenon3) 26) (= (slew_time phenomenon3 phenomenon4) 26) (= (slew_time star5 star0) 37) (= (slew_time star0 star5) 37) (= (slew_time star5 groundstation1) 9) (= (slew_time groundstation1 star5) 9) (= (slew_time star5 groundstation2) 63) (= (slew_time groundstation2 star5) 63) (= (slew_time star5 phenomenon3) 11) (= (slew_time phenomenon3 star5) 11) (= (slew_time star5 phenomenon4) 65) (= (slew_time phenomenon4 star5) 65) (= (slew_time phenomenon6 star0) 78) (= (slew_time star0 phenomenon6) 78) (= (slew_time phenomenon6 groundstation1) 18) (= (slew_time groundstation1 phenomenon6) 18) (= (slew_time phenomenon6 groundstation2) 51) (= (slew_time groundstation2 phenomenon6) 51) (= (slew_time phenomenon6 phenomenon3) 15) (= (slew_time phenomenon3 phenomenon6) 15) (= (slew_time phenomenon6 phenomenon4) 3) (= (slew_time phenomenon4 phenomenon6) 3) (= (slew_time phenomenon6 star5) 30) (= (slew_time star5 phenomenon6) 30) (= (data_stored) 0))
 (:goal (and (have_image phenomenon4 thermograph0) (have_image star5 thermograph0) (have_image phenomenon6 thermograph0)))
 (:metric minimize (total-time))
)
