(define (problem socs2025_match_cellar_2-problem)
 (:domain socs2025_match_cellar_2-domain)
 (:init (handfree) (= (num_matches) 4) (= (num_fuses) 8) (= (num_lit_matches) 0) (= (num_mended_fuses) 0))
 (:goal (and (= (num_mended_fuses) 8)))
 (:metric minimize (total-time))
)
