(define (problem socs2025_match_cellar_6-problem)
 (:domain socs2025_match_cellar_6-domain)
 (:init (handfree) (= (num_matches) 8) (= (num_fuses) 16) (= (num_lit_matches) 0) (= (num_mended_fuses) 0))
 (:goal (and (= (num_mended_fuses) 16)))
 (:metric minimize (total-time))
)
