(define (problem socs2025_rovers_5-problem)
 (:domain socs2025_rovers_5-domain)
 (:objects
   rover0 rover1 - rover
   waypoint0 waypoint1 waypoint2 waypoint3 - waypoint
   rover0store rover1store - store
   camera0 camera1 camera2 - camera
   colour high_res low_res - mode
   general - lander
   objective0 objective1 objective2 - objective
 )
 (:init (visible waypoint0 waypoint2) (visible waypoint2 waypoint0) (visible waypoint1 waypoint0) (visible waypoint0 waypoint1) (visible waypoint1 waypoint3) (visible waypoint3 waypoint1) (visible waypoint2 waypoint1) (visible waypoint1 waypoint2) (visible waypoint3 waypoint0) (visible waypoint0 waypoint3) (visible waypoint3 waypoint2) (visible waypoint2 waypoint3) (at_rock_sample waypoint0) (in_sun waypoint0) (at_soil_sample waypoint1) (at_rock_sample waypoint1) (at_soil_sample waypoint2) (at_soil_sample waypoint3) (at_lander general waypoint3) (channel_free general) (at_ rover0 waypoint0) (available rover0) (store_of rover0store rover0) (empty rover0store) (equipped_for_rock_analysis rover0) (equipped_for_imaging rover0) (can_traverse rover0 waypoint0 waypoint1) (can_traverse rover0 waypoint1 waypoint0) (can_traverse rover0 waypoint0 waypoint3) (can_traverse rover0 waypoint3 waypoint0) (at_ rover1 waypoint0) (available rover1) (store_of rover1store rover1) (empty rover1store) (equipped_for_soil_analysis rover1) (equipped_for_imaging rover1) (can_traverse rover1 waypoint0 waypoint1) (can_traverse rover1 waypoint1 waypoint0) (can_traverse rover1 waypoint1 waypoint2) (can_traverse rover1 waypoint2 waypoint1) (can_traverse rover1 waypoint1 waypoint3) (can_traverse rover1 waypoint3 waypoint1) (on_board camera0 rover1) (calibration_target camera0 objective1) (supports camera0 high_res) (supports camera0 low_res) (on_board camera1 rover1) (calibration_target camera1 objective1) (supports camera1 colour) (supports camera1 high_res) (on_board camera2 rover0) (calibration_target camera2 objective1) (supports camera2 colour) (supports camera2 high_res) (supports camera2 low_res) (visible_from objective0 waypoint0) (visible_from objective0 waypoint1) (visible_from objective0 waypoint2) (visible_from objective0 waypoint3) (visible_from objective1 waypoint0) (visible_from objective1 waypoint1) (visible_from objective1 waypoint2) (visible_from objective2 waypoint0) (visible_from objective2 waypoint1) (visible_from objective2 waypoint2) (= (recharge_duration rover0) 200) (= (recharge_duration_max rover0) 533) (= (recharge_duration_1 rover0) 6) (= (recharge_duration_2 rover0) 13) (= (recharge_duration_3 rover0) 20) (= (recharge_duration_4 rover0) 26) (= (recharge_duration_5 rover0) 33) (= (recharge_duration_6 rover0) 40) (= (recharge_duration_8 rover0) 53) (= (recharge_duration rover1) 176) (= (recharge_duration_max rover1) 470) (= (recharge_duration_1 rover1) 5) (= (recharge_duration_2 rover1) 11) (= (recharge_duration_3 rover1) 17) (= (recharge_duration_4 rover1) 23) (= (recharge_duration_5 rover1) 29) (= (recharge_duration_6 rover1) 35) (= (recharge_duration_8 rover1) 47))
 (:goal (and (communicated_soil_data waypoint1) (communicated_soil_data waypoint2) (communicated_rock_data waypoint0) (communicated_rock_data waypoint1) (communicated_image_data objective0 high_res) (communicated_image_data objective2 high_res) (communicated_image_data objective0 colour)))
 (:metric minimize (total-time))
)
